live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

# NEW style
# [colors.primary]
# background = "0x1d2021"
# foreground = "0xd4be98"
#
# [colors.normal]
# black = "0x32302f"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"
#
# [colors.bright]
# black = "0x32302f"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xd4be98"
# yellow = "0xd8a657"

# OLD style
[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[colors.normal]
black = "0x1d2021"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xd5c4a1"

[colors.bright]
black = "0x665c54"
red = "0xfe8019"
green = "0x3c3836"
yellow = "0x504945"
blue = "0xbdae93"
magenta = "0xebdbb2"
cyan = "0xd65d0e"
white = "0xfbf1c7"

[cursor]
# blinking = "On"

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"

[env]
TERM = "alacritty"

[font]
size = 16

[font.normal]
family = "Roboto Mono"
style = "Medium"

[window]
dynamic_title = true
title = "Terminal"
opacity = 1 # default 1.0

# [[keyboard.bindings]]
# chars = "\u001BF"
# key = "Right"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001BB"
# key = "Left"
# mods = "Alt"
