live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"

[colors.normal]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[cursor]
# blinking = "On"

[env]
TERM = "alacritty"

[font]
size = 16

[font.normal]
family = "Roboto Mono"
style = "Medium"

[window]
dynamic_title = true
title = "Terminal"
opacity = 1 # default 1.0

# [[keyboard.bindings]]
# chars = "\u001BF"
# key = "Right"
# mods = "Alt"

# [[keyboard.bindings]]
# chars = "\u001BB"
# key = "Left"
# mods = "Alt"
